config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  devise_for :users
  root to: 'pages#home'

  resources :items, except: %i[index new create show]
  resources :carts do
    resources :orders
  end
  resources :orders, only: %i[destroy show]

  resources :kitchens do
    resources :reviews, only: %i[new create]
    resources :items, only: %i[new create show]
  end
  resources :reviews, only: %i[destroy]

  resources :stations do
    resources :bookings, only: %i[new index create show]
  end
  resources :bookings, only: %i[destroy]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :kitchen
  belongs_to :station

  validates :date, :price, presence: true
  validates :price, numericality: true

  def calculate_price
    # check for the date and the shift type
    # if weekend multiply by corresponding price Date.today.wday

    period = %w[breakfast lunch dinner]
    if (date.wday == 5 || date.wday == 6) && period == 'dinner'
      self.price = 400
    elsif (date.wday == 6 || date.wday == 7) && period == 'lunch'
      self.price = 150
    else
      self.price = 100
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]

  def index
    @bookings = Booking.where(user_id: current_user.id)
    @station = Station.find(params[:station_id])
  end

  def show; end

  def new
    @station = Station.find(params[:station_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @station = Station.find(params[:station_id])
    @booking.station = @station
    @booking.user = current_user
    @booking.calculate_price
    if @booking.save
      redirect_to station_bookings_path(@booking.station),
                  notice: 'Booking successfully created.'
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to stations_path, notice: 'booking successfully destroyed.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date, :kitchen_id, :period)
  end
end

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>
<%= link_to 'More information', station_booking_path(@station, booking) %>
<%= link_to "Delete booking", booking_path(booking), method: :delete, data: {confirm:"Are you sure you want to delete this?"} %>
  <%= booking.price.to_i %>
  <%= booking.date %>
<% end %>

app/views/bookings/new.html.erb
<h3 class='text-center size-link my-3'>book for your restaurant</h3>

<%= render 'shared/form_booking' %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <%= link_to 'Back', root_path %>
      </div>
    </div>
  </div>

app/views/bookings/show.html.erb
  <%= @booking.price.to_i %>
  <%= @booking.date %>