config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  devise_for :users
  root to: 'pages#home'

  resources :items, except: %i[index new create show]
  resources :carts do
    resources :orders
  end
  resources :orders, only: %i[destroy show]

  resources :kitchens do
    resources :reviews, only: %i[new create]
    resources :items, only: %i[new create show]
  end
  resources :reviews, only: %i[destroy]

  resources :stations do
    resources :bookings, only: %i[new index create show]
  end
  resources :bookings, only: %i[destroy]
end

app/views/shared/_cart.html.erb
<% if cart_has_items %>
  <button class="btn btn-light"><%= link_to cart_path(@cart) do %>
      <i class="fa" style="font-size:24px">&#xf07a;</i>
      <span class='badge badge-warning' id='lblCartCount'><%= @cart.line_items.map(&:quantity).sum %></span>
  </button>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>
  </div>
  <div class="footer-copyright" >
    <%= link_to "Become a Chef", new_user_registration_path(chef: true), class: "btn btn-ghost" %>
  </div>
</div>

app/views/shared/_form.html.erb
<div class="bg-section-kitchen page-hero-section create-item-hero">
  <div class="wrapper w-container">
    <h1 class="page-hero-header">Your Menu</h1>
  </div>
</div>


<div class="section pattern-section no-top-padding">
  <div class="wrapper w-container">
    <div class="reservation w-form">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-12">
            <div class="form-item">
              <h2 class="text-center">Describe your dish</h2>
              <%= simple_form_for [@kitchen, @item] do |f| %>
              <%= f.input :dish %>
              <%= f.input :ingredient %>
              <%= f.input :description %>
              <%= f.input :category, collection: Item::CATEGORIES %>
              <div class="form-group">
                <label class="text required" for="item_description">Allergens <abbr title="required" data-children-count="0">*</abbr></label>
                <br>

                <input type="hidden" name="post[category_ids][]" value="">
                <div class="category-choices">
                  <% Item::ALLERGENS.each do |allergen| %>
                    <input type="checkbox" class="hidden" value="<%= "#{allergen}" %>" name="item[allergen][]" id="item_allergen_<%= "#{allergen}" %>">
                    <label class="category-choice" for="item_allergen_<%= "#{allergen}" %>">
                      <%= allergen %>
                      <i class="fa fa-check"></i>
                    </label>
                  <% end %>
                </div>
              </div>
              <%= f.input :price, placeholder: "Price in £" %>
              <%= f.input :photo, as: :file %>
              <%= f.button :submit, class: 'main-button', value: 'Create Dish'%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
     </div>
  </div>
</div>

app/views/shared/_form_booking.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for [@station, @booking] do |f| %>
        <%= f.input :date %>
        <%= f.input :period, collection: ["breakfast", "lunch", "dinner"] %>
        <%= f.select :kitchen_id, current_user.kitchens.map { |kitchen| [kitchen.name, kitchen.id] } %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_form_kitchen.html.erb
<div class="bg-section-kitchen page-hero-section create-kitchen-hero">
  <div class="wrapper w-container">
    <h1 class="page-hero-header">Your Kitchen</h1>
  </div>
</div>

<div class="section pattern-section no-top-padding">
  <div class="wrapper w-container">
    <div class="reservation w-form">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-12">
            <div class="form-item">
            <h2 class="text-center">Your details</h2>
            <%= simple_form_for @kitchen do |f| %>
              <%= f.input :name %>
              <%= f.input :cuisine, collection: Kitchen::CUISINE %>
              <%= f.input :photo, as: :file %>
              <%= f.button :submit, class: 'main-button' %>
            <% end %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<button type="button" class="main-button-green" data-toggle="modal" data-target="#exampleModalCenter">
  Confirm order
</button>

<!-- Modal -->

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Your Order #<%= @order.id %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'shared/payment_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="main-button-danger" data-dismiss="modal">Close</button>
        <button class="payment-modal main-button-green">Pay</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">


  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dc8t19jnn/image/upload/v1599762816/LogoMakr_04z4SS_jywgoa.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
          <div id="hideCart">
            <%= render 'shared/cart' %>
          </div>
          </li>
          <!-- <li class="nav-item">
            <%= link_to "Create new Kitchen", new_kitchen_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Account", edit_user_registration_path , class: "nav-link" %>
          </li> -->
        <li class="nav-item dropdown">
          <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.kitchens.any? %>
              <%= link_to "My Kitchen", kitchen_path(current_user.kitchens.first), class: "dropdown-item" %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_payment_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="form-item">
        <h5 class="text-center">Confirm Payment</h5>
        <div class="row display-tr ml-1">
          <div class="display-td mb-3">
            <img class="img-responsive pull-center" src="https://www.merchantequip.com/images/logos/visa-mastercard-211x65.gif">
          </div>
        </div>
        <label for="fname"></i> Cardholder name</label>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
          </div>
          <input type="text" class="form-control" placeholder="John More Doe">
        </div>
        <label for="ccnum"> Card number</label>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="far fa-credit-card"></i></span>
          </div>
          <input type="text" class="form-control" placeholder="1111-2222-3333-4444">
        </div>
        <label for="expmonth">Exp Date</label>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="far fa-calendar"></i></span>
          </div>
          <input type="text" class="form-control" placeholder="MM/YY">
        </div>
        <label for="cvv">CVV</label>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><i class="fas fa-lock"></i></span>
          </div>
          <input type="text" class="form-control" placeholder="352">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_progress_bar.html.erb
<div class="progress">
  <ul>
    <li class="in-progress">
      <%= cl_image_tag("review.png_vblhbv.png") %><br>
      <i class="fas fa-sync-alt"></i>
      <p>Review your order</p>
    </li>
    <li>
      <%= cl_image_tag("payment.png") %><br>
      <i class="fas fa-times-circle"></i>
      <p>Payment</p>
    </li>
    <li>
      <%= cl_image_tag("enjoy.png") %><br>
      <i class="fas fa-times-circle"></i>
      <p>Enjoy</p>
    </li>
  </ul>
</div>