config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  devise_for :users
  root to: 'pages#home'

  resources :items, except: %i[index new create show]
  resources :carts do
    resources :orders
  end
  resources :orders, only: %i[destroy show]

  resources :kitchens do
    resources :reviews, only: %i[new create]
    resources :items, only: %i[new create show]
  end
  resources :reviews, only: %i[destroy]

  resources :stations do
    resources :bookings, only: %i[new index create show]
  end
  resources :bookings, only: %i[destroy]
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  # belongs_to :order
  # has_one :user

  def add_item(item)
    current_item = line_items.find_by(item_id: item.id)
    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.new(item_id: item.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum(&:total_price)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!

  def index
    @carts = Cart.all
  end

  def show; end

  def new
    @cart = Cart.new
  end

  def edit; end

  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      redirect_to @cart, alert: 'Cart was successfully created.'
    else
      render :new
    end
  end

  def update
    if @cart.update(cart_params)
      redirect_to @cart, alert: 'Cart was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @cart.destroy if @cart_id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to root_path, alert: 'Your cart is empty!'
  end

  private

  def set_cart
    @cart = Cart.find(params[:id])
  end

  def cart_params
    params.fetch(:cart, {})
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, alert: "That cart doesn't exit"
  end
end

app/views/carts/show.html.erb
<div class="progress-section pattern-section no-top-padding">
<div class="my-container w-container">
  <div class="cart-reservation w-form">
    <%= render 'shared/progress_bar' %>
  </div>
</div>
</div>

<div class="section pattern-section no-top-padding">
  <div class="wrapper w-container">
    <div class="cart-reservation w-form">
      <div class="container cart-page">
        <h3 class="text-center">Review your order</h3>
        <table class="cart-table">
          <tr>
            <th class="cart-text">Items</th>
            <th class="cart-text">Quantity</th>
            <th class="cart-text text-right">Subtotal</th>
          </tr>
          <% @cart.line_items.each do |line_item| %>
            <tr>
              <td class="item-data">
                <div class="cart-info">
                  <% if line_item.item.photo.attached? %>
                    <%= cl_image_tag line_item.item.photo.key, class: "img-cart" %>
                  <% end %>
                  <div>
                    <h4 class="item-tag"><%= line_item.item.dish.capitalize %></h4>
                    <small>Price: £<%= line_item.item.price %></small>
                    <br>
                    <%= link_to '', line_item, class: 'far fa-trash-alt icon-black', method: :delete %>
                    <%#= link_to 'Delete item', line_item, method: :delete %>
                  </div>
                </div>
              </td>
              <td class="item-data"><input type="number" value="<%= line_item.quantity %>"></td>
              <td class="item-data">£<%= line_item.total_price %></td>
            </tr>
          <% end %>
        </table>
        <div class="total-price">
          <table class="total-table">
            <tr>
              <td class="item-data">Subtotal</td>
              <td class="item-data">£<%= @cart.total_price %></td>
            </tr>
            <tr>
              <td class="item-data">VAT</td>
              <td class="item-data">£<%=  total = (@cart.total_price * 20) / 100 %></td>
            </tr>
              <tr>
              <td class="item-data">Total</td>
              <td class="item-data">£<%= total + @cart.total_price %></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="container d-flex justify-content-between mt-4">
      <%#= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "btn btn-primary" %>
      <%= link_to 'Keep Shopping', kitchens_path, class: 'main-button' %>
      <%= link_to 'Checkout', cart_orders_path(@cart), method: :post, class: 'main-button' %>
      </div>
    </div>
  </div>
</div>